### ISSUE TITLE
Re-submission ToDo list

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/paper-Olurida-gene#19]
- [x] Create hi-res figure files (.eps or .png)
- [x] Create separate Word (.docx) files for each table
- [x] Upload files to [PeerJ](https://peerj.com/manuscripts/12793/files)
- [ ] Check references within text and in references list
- [ ] Upload revised manuscript with tracked changes to [PeerJ](https://peerj.com/manuscripts/12793/files)
- [ ] Upload rebuttal letter to [PeerJ](https://peerj.com/manuscripts/12793/files)
